{% set name = "pywwa" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pywwa-{{ version }}.tar.gz
  sha256: c97ccee12445ddf8366f25c3fc45b344a532f7389de0c50876977b3d7baf1030

build:
  entry_points:
    - pywwa-parse-afos-dump = pywwa.workflows.afos_dump:main
    - pywwa-parse-aviation = pywwa.workflows.aviation:main
    - pywwa-parse-bufr-surface = pywwa.workflows.bufr_surface:main
    - pywwa-parse-cf6 = pywwa.workflows.cf6:main
    - pywwa-parse-cli = pywwa.workflows.cli:main
    - pywwa-parse-dsm = pywwa.workflows.dsm:main
    - pywwa-parse-dsm2afos = pywwa.workflows.dsm2afos:main
    - pywwa-parse-ero = pywwa.workflows.ero:main
    - pywwa-parse-fake-afos-dump = pywwa.workflows.fake_afos_dump:main
    - pywwa-parse-fd = pywwa.workflows.fd:main
    - pywwa-parse-ffg = pywwa.workflows.ffg:main
    - pywwa-parse-gairmet = pywwa.workflows.gairmet:main
    - pywwa-parse-generic = pywwa.workflows.generic:main
    - pywwa-parse-gini2gis = pywwa.workflows.gini2gis:main
    - pywwa-parse-hml = pywwa.workflows.hml:main
    - pywwa-parse-lsr = pywwa.workflows.lsr:main
    - pywwa-parse-mcd = pywwa.workflows.mcd:main
    - pywwa-parse-metar = pywwa.workflows.metar:main
    - pywwa-parse-mos = pywwa.workflows.mos:main
    - pywwa-parse-nexrad3-attr = pywwa.workflows.nexrad3_attr:main
    - pywwa-parse-nldn = pywwa.workflows.nldn:main
    - pywwa-parse-pirep = pywwa.workflows.pirep:main
    - pywwa-parse-rr7 = pywwa.workflows.rr7:main
    - pywwa-parse-scp = pywwa.workflows.scp:main
    - pywwa-parse-shef = pywwa.workflows.shef:main
    - pywwa-parse-spc = pywwa.workflows.spc:main
    - pywwa-parse-spe = pywwa.workflows.spe:main
    - pywwa-parse-split-mav = pywwa.workflows.split_mav:main
    - pywwa-parse-sps = pywwa.workflows.sps:main
    - pywwa-parse-taf = pywwa.workflows.taf:main
    - pywwa-parse-vtec = pywwa.workflows.vtec:main
    - pywwa-parse-watch = pywwa.workflows.watch:main
    - pywwa-parse-xteus = pywwa.workflows.xteus:main
    - pywwa-spammer = pywwa.workflows.spammer:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - click
    - geopandas
    - metpy
    - metar >=1.7.0
    - netcdf4
    - numpy
    - pandas
    - pint
    - psycopg
    - pybufrkit
    - pyiem
    - pymemcache
    - pyproj
    - requests
    - shapely
    - sqlalchemy
    - treq
    - twisted

test:
  imports:
    - pywwa
  commands:
    - pip check
    - pywwa-parse-afos-dump --help
    - pywwa-parse-aviation --help
    - pywwa-parse-bufr-surface --help
    - pywwa-parse-cf6 --help
    - pywwa-parse-cli --help
    - pywwa-parse-dsm --help
    - pywwa-parse-dsm2afos --help
    - pywwa-parse-ero --help
    - pywwa-parse-fake-afos-dump --help
    - pywwa-parse-fd --help
    - pywwa-parse-ffg --help
    - pywwa-parse-gairmet --help
    - pywwa-parse-generic --help
    - pywwa-parse-gini2gis --help
    - pywwa-parse-hml --help
    - pywwa-parse-lsr --help
    - pywwa-parse-mcd --help
    - pywwa-parse-metar --help
    - pywwa-parse-mos --help
    - pywwa-parse-nexrad3-attr --help
    - pywwa-parse-nldn --help
    - pywwa-parse-pirep --help
    - pywwa-parse-rr7 --help
    - pywwa-parse-scp --help
    - pywwa-parse-shef --help
    - pywwa-parse-spc --help
    - pywwa-parse-spe --help
    - pywwa-parse-split-mav --help
    - pywwa-parse-sps --help
    - pywwa-parse-taf --help
    - pywwa-parse-vtec --help
    - pywwa-parse-watch --help
    - pywwa-parse-xteus --help
    - pywwa-spammer --help
  requires:
    - pip

about:
  home: https://github.com/akrherz/pyWWA
  summary: A suite of parsers and utils for NWS products.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
